##### What is Pandas?
Python library used for working with structured data sets (tables). It has functions for analyzing, cleaning, exploring, and manipulating data. Similar to data tables in SQL and Excel.

#### 0 install pandas

In [1]:
!pip install pandas

Requirement already satisfied: pandas in d:\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: numpy>=1.15.4 in d:\anaconda3\lib\site-packages (from pandas) (1.19.2)
Requirement already satisfied: pytz>=2017.2 in d:\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in d:\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [2]:
# import pandas
import pandas as pd

In [3]:
pd.__version__ # check installed pandas version

'1.1.3'

##### What is Dataframe?
It's a structured data constructed with rows and columns, similar to a SQL tables or Excel tables

#### 1 Create Dataframe

In [136]:
# using a List
df = pd.DataFrame([11,22,33], columns=['marks'])
print(df)

   marks
0     11
1     22
2     33

In [5]:
print(type(df)) # check data type

<class 'pandas.core.frame.DataFrame'>

In [6]:
# using Dictionary of Lists
data = {
    'Name': ['Yogesh', 'Yubraj', 'Nikhil', 'Ishita'],
    'Age': [16,17,18,19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [7]:
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0  Yogesh   16   90000
1  Yubraj   17   70000
2  Nikhil   18   50000
3  Ishita   19   30000

In [8]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

#### 2 Basic Dataframe Understanding

In [9]:
df.head(2) # top rows

     Name  Age  Salary
0  Yogesh   16   90000
1  Yubraj   17   70000

In [10]:
df.tail(2) # last rows

     Name  Age  Salary
2  Nikhil   18   50000
3  Ishita   19   30000

In [11]:
df.shape # returns a tuple containing the shape of the DataFrame - rows & columns

(4, 3)

In [12]:
df.columns # list of column names in a dataframe

Index(['Name', 'Age', 'Salary'], dtype='object')

In [13]:
df.rename(columns={'Salary': 'Monthly_Salary'})

     Name  Age  Monthly_Salary
0  Yogesh   16           90000
1  Yubraj   17           70000
2  Nikhil   18           50000
3  Ishita   19           30000

In [14]:
df

     Name  Age  Salary
0  Yogesh   16   90000
1  Yubraj   17   70000
2  Nikhil   18   50000
3  Ishita   19   30000

In [15]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True) # rename column name/s

In [16]:
df

     Name  Age  Monthly_Salary
0  Yogesh   16           90000
1  Yubraj   17           70000
2  Nikhil   18           50000
3  Ishita   19           30000

In [17]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [18]:
df.describe() # describe method generates descriptive statistics of DataFrame, only for numerical-value columns

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

#### 3 Save and Load data from csv

In [19]:
df.to_csv('Test_data.csv', index=False) # save file - export data frame

In [20]:
load_df= pd.read_csv('Test_data.csv') # load file - import dataframe
load_df

     Name  Age  Monthly_Salary
0  Yogesh   16           90000
1  Yubraj   17           70000
2  Nikhil   18           50000
3  Ishita   19           30000

#### 4 Rows & Columns - Selection

In [21]:
# select single column
df[['Name']]

     Name
0  Yogesh
1  Yubraj
2  Nikhil
3  Ishita

In [22]:
# select multiple columns
df[['Name', 'Monthly_Salary']]

     Name  Monthly_Salary
0  Yogesh           90000
1  Yubraj           70000
2  Nikhil           50000
3  Ishita           30000

In [88]:
# select single row || loc - label based index
df.loc[df.Name=='Ishita']

     Name  Age   Salary Team        DOJ  Month
3  Ishita   19  30000.0   DA 2024-03-03      3

In [90]:
# select multiple rows || loc - label based index
df.loc[(df.Name=='Yubraj') & (df.Salary>=50000)]

     Name  Age   Salary Team        DOJ  Month
1  Yubraj   17  70000.0   HR 2024-01-15      1

In [105]:
#df.loc[0:2]
df[['Name','Age']]

     Name  Age
0  Yogesh   16
1  Yubraj   17
2  Nikhil   18
3  Ishita   19

In [26]:
# Select Rows || iloc - index-value based
# df.iloc[0]
df.iloc[0:2] # [start:stop:step]

     Name  Age  Monthly_Salary
0  Yogesh   16           90000
1  Yubraj   17           70000

#### 5 Filter Dataframe - Filtering by column values

In [27]:
df

     Name  Age  Monthly_Salary
0  Yogesh   16           90000
1  Yubraj   17           70000
2  Nikhil   18           50000
3  Ishita   19           30000

In [28]:
df_age_filter = df[df['Age'] >= 18] # filter and store dataframe in a new variable

In [29]:
df_age_filter

     Name  Age  Monthly_Salary
2  Nikhil   18           50000
3  Ishita   19           30000

In [30]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 50000)] # multiple filter conditions

     Name  Age  Monthly_Salary
2  Nikhil   18           50000

In [31]:
df.where(df['Age'] >= 18) # where function replace values in a DataFrame based on a condition

     Name   Age  Monthly_Salary
0     NaN   NaN             NaN
1     NaN   NaN             NaN
2  Nikhil  18.0         50000.0
3  Ishita  19.0         30000.0

In [32]:
df.where(df['Age'] >= 18, other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Nikhil            18          50000
3        Ishita            19          30000

#### 6 Rows and Columns - Operation (Add, update, delete)

In [33]:
df

     Name  Age  Monthly_Salary
0  Yogesh   16           90000
1  Yubraj   17           70000
2  Nikhil   18           50000
3  Ishita   19           30000

In [34]:
# Create a new column
df['Team'] = ['CEO', 'HR', 'CTO', 'DA']
df

     Name  Age  Monthly_Salary Team
0  Yogesh   16           90000  CEO
1  Yubraj   17           70000   HR
2  Nikhil   18           50000  CTO
3  Ishita   19           30000   DA

In [35]:
# Add new columns using existing column/s
df['Bonus'] = df['Monthly_Salary'] * 0.20
df

     Name  Age  Monthly_Salary Team    Bonus
0  Yogesh   16           90000  CEO  18000.0
1  Yubraj   17           70000   HR  14000.0
2  Nikhil   18           50000  CTO  10000.0
3  Ishita   19           30000   DA   6000.0

In [36]:
# Add new row - at the end of dataframe
df.loc[len(df)] = ['ABC', 21, 21000, 'IT', 2000]
df

     Name  Age  Monthly_Salary Team    Bonus
0  Yogesh   16           90000  CEO  18000.0
1  Yubraj   17           70000   HR  14000.0
2  Nikhil   18           50000  CTO  10000.0
3  Ishita   19           30000   DA   6000.0
4     ABC   21           21000   IT   2000.0

In [37]:
# update value in dataframe using index-name
df.loc[0, 'Monthly_Salary'] = 95000
df

     Name  Age  Monthly_Salary Team    Bonus
0  Yogesh   16           95000  CEO  18000.0
1  Yubraj   17           70000   HR  14000.0
2  Nikhil   18           50000  CTO  10000.0
3  Ishita   19           30000   DA   6000.0
4     ABC   21           21000   IT   2000.0

In [38]:
# update value in dataframe using column-value
df.loc[df.Name=='Madhav','Monthly_Salary'] = 90000
df

     Name  Age  Monthly_Salary Team    Bonus
0  Yogesh   16           95000  CEO  18000.0
1  Yubraj   17           70000   HR  14000.0
2  Nikhil   18           50000  CTO  10000.0
3  Ishita   19           30000   DA   6000.0
4     ABC   21           21000   IT   2000.0

In [39]:
# delete value - rows and columns

In [40]:
# delete row using column-value filter
df = df.drop(df[df.Name == 'ABC'].index) # delete row, axis= 0

In [41]:
# delete row using index-name filter
df.drop(1, axis=0)

     Name  Age  Monthly_Salary Team    Bonus
0  Yogesh   16           95000  CEO  18000.0
2  Nikhil   18           50000  CTO  10000.0
3  Ishita   19           30000   DA   6000.0

In [42]:
df.drop('Bonus', axis=1, inplace=True) # delete one column
# df.drop(['Bonus', 'Team'], axis=1, inplace=True) # delete multiple columns

In [43]:
df

     Name  Age  Monthly_Salary Team
0  Yogesh   16           95000  CEO
1  Yubraj   17           70000   HR
2  Nikhil   18           50000  CTO
3  Ishita   19           30000   DA

In [44]:
df.rename(columns={'Monthly_Salary': 'Salary'}, inplace=True) # rename column name

In [45]:
# sort values - order values in dataframe by asc or desc order
df.sort_values('Salary') #ascending order, by default

     Name  Age  Salary Team
3  Ishita   19   30000   DA
2  Nikhil   18   50000  CTO
1  Yubraj   17   70000   HR
0  Yogesh   16   95000  CEO

In [46]:
# sort values in descending order
df.sort_values('Salary', ascending=False)

     Name  Age  Salary Team
0  Yogesh   16   95000  CEO
1  Yubraj   17   70000   HR
2  Nikhil   18   50000  CTO
3  Ishita   19   30000   DA

#### 7 working with date value

In [47]:
# create a date column - date of joining
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']
df

     Name  Age  Salary Team         DOJ
0  Yogesh   16   95000  CEO  2024-01-01
1  Yubraj   17   70000   HR  2024-01-15
2  Nikhil   18   50000  CTO  2024-03-28
3  Ishita   19   30000   DA  2024-03-03

In [48]:
df['DOJ'].dtype # object-type value

dtype('O')

In [49]:
df['DOJ'] = pd.to_datetime(df['DOJ']) # change to date-time type

In [50]:
df['DOJ'].dtype # date-time type

dtype('<M8[ns]')

In [51]:
df1 = df

In [52]:
# creating a new column with incorrect date format
df1['DOJ2'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025']
df1

     Name  Age  Salary Team        DOJ        DOJ2
0  Yogesh   16   95000  CEO 2024-01-01  01-01-2025
1  Yubraj   17   70000   HR 2024-01-15  15-01-2025
2  Nikhil   18   50000  CTO 2024-03-28  28-03-2025
3  Ishita   19   30000   DA 2024-03-03  03-03-2025

In [53]:
df1['DOJ2'].dtype  # object-type value

dtype('O')

In [54]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format = '%d-%m-%Y') # change to date-time type using date-format

In [55]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [56]:
df = df.drop('DOJ2', axis=1)
df

     Name  Age  Salary Team        DOJ
0  Yogesh   16   95000  CEO 2024-01-01
1  Yubraj   17   70000   HR 2024-01-15
2  Nikhil   18   50000  CTO 2024-03-28
3  Ishita   19   30000   DA 2024-03-03

In [57]:
# extract year, month, week, day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: object

In [58]:
# create new column using month extract function from DOJ column
df['Month'] = df['DOJ'].dt.month

In [59]:
df

     Name  Age  Salary Team        DOJ  Month
0  Yogesh   16   95000  CEO 2024-01-01      1
1  Yubraj   17   70000   HR 2024-01-15      1
2  Nikhil   18   50000  CTO 2024-03-28      3
3  Ishita   19   30000   DA 2024-03-03      3

In [60]:
df['DOJ'] + pd.Timedelta(days=90) # add 90 days to DOJ column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[ns]

#### 8 Handling Missing Values

In [61]:
df

     Name  Age  Salary Team        DOJ  Month
0  Yogesh   16   95000  CEO 2024-01-01      1
1  Yubraj   17   70000   HR 2024-01-15      1
2  Nikhil   18   50000  CTO 2024-03-28      3
3  Ishita   19   30000   DA 2024-03-03      3

In [62]:
df.isnull() #  Detect missing values

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [63]:
import numpy as np  # to create null values below

In [64]:
df.loc[df.Name=='Rishabh', 'Salary'] = np.nan # adding a null value

In [65]:
df

     Name  Age   Salary Team        DOJ  Month
0  Yogesh   16  95000.0  CEO 2024-01-01      1
1  Yubraj   17  70000.0   HR 2024-01-15      1
2  Nikhil   18  50000.0  CTO 2024-03-28      3
3  Ishita   19  30000.0   DA 2024-03-03      3

In [66]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [67]:
df.isnull().sum() # count of null values by columns

Name      0
Age       0
Salary    0
Team      0
DOJ       0
Month     0
dtype: int64

In [68]:
df.fillna(0) # fill null values with 0

     Name  Age   Salary Team        DOJ  Month
0  Yogesh   16  95000.0  CEO 2024-01-01      1
1  Yubraj   17  70000.0   HR 2024-01-15      1
2  Nikhil   18  50000.0  CTO 2024-03-28      3
3  Ishita   19  30000.0   DA 2024-03-03      3

In [69]:
df.loc[df.Name=='Ishita', 'Salary'] = 30000

In [70]:
df

     Name  Age   Salary Team        DOJ  Month
0  Yogesh   16  95000.0  CEO 2024-01-01      1
1  Yubraj   17  70000.0   HR 2024-01-15      1
2  Nikhil   18  50000.0  CTO 2024-03-28      3
3  Ishita   19  30000.0   DA 2024-03-03      3

#### 9 Aggregation and Group By

In [71]:
df['Month'].value_counts() # frequency of values in month column

3    2
1    2
Name: Month, dtype: int64

In [72]:
df[df['Month']==1].value_counts() # frequency of values in month column where month=1

Name    Age  Salary   Team  DOJ         Month
Yubraj  17   70000.0  HR    2024-01-15  1        1
Yogesh  16   95000.0  CEO   2024-01-01  1        1
dtype: int64

In [73]:
# aggregation based on group by
df.groupby('Month')['Salary'].sum() # sum of salary by month

Month
1    165000.0
3     80000.0
Name: Salary, dtype: float64

In [74]:
# different aggregation on different columns
df.groupby('Month').agg({'Salary': 'mean', 'Name': 'count'})

        Salary  Name
Month
1      82500.0     2
3      40000.0     2

#### 10 Concatenate and Merge Dataframe (JOINS)

In [75]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [76]:
df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

##### What is Concatenate:
Combine objects along a particular axis.

In [77]:
# Concatenate: vertical / row level / top on top
pd.concat([df1, df2], axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [78]:
# Concatenate: horizontal / column level / side on side
pd.concat([df1, df2], axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

##### Merge in Pandas
Performs join operations similar to relational databases like SQL JOINS

In [79]:
# merge = join
pd.merge(df1, df2, how='inner', on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [80]:
pd.merge(df1, df2, how='inner', left_on='ID', right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

#### 11 AI and ChatGPT

In [81]:
df

     Name  Age   Salary Team        DOJ  Month
0  Yogesh   16  95000.0  CEO 2024-01-01      1
1  Yubraj   17  70000.0   HR 2024-01-15      1
2  Nikhil   18  50000.0  CTO 2024-03-28      3
3  Ishita   19  30000.0   DA 2024-03-03      3

In [82]:
# Prompt to filter salary > 70000 and January employees

In [83]:
# Method-1: basic filter
df[(df['Month'] == 1) & (df['Salary'] >= 70000)]

     Name  Age   Salary Team        DOJ  Month
0  Yogesh   16  95000.0  CEO 2024-01-01      1
1  Yubraj   17  70000.0   HR 2024-01-15      1

In [84]:
# Method-2: query method
df.query("Month == 1 and Salary >= 70000")

     Name  Age   Salary Team        DOJ  Month
0  Yogesh   16  95000.0  CEO 2024-01-01      1
1  Yubraj   17  70000.0   HR 2024-01-15      1

##### Home work: Create a dataframe to practice pivot table in pandas (using AI prompt)

In [112]:
# importing pandas
import pandas as pd

# creating dataframe
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'sabzi', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli      sabzi         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

In [110]:
pivot = df.pivot_table(index=['Product'],
                       values=['Amount'],
                       aggfunc='sum')
print(pivot)

          Amount
Product
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610

In [113]:
# creating pivot table of total
# sales category-wise aggfunc = 'sum'
pivot = df.pivot_table(index=['Category'],
                       values=['Amount'],
                       aggfunc='sum')
print(pivot)

           Amount
Category
Fruit        1701
Vegetable     958
sabzi         239

In [120]:
df['Category']

0    Vegetable
1        sabzi
2        Fruit
3        Fruit
4    Vegetable
5        Fruit
6    Vegetable
7        Fruit
Name: Category, dtype: object

In [116]:
pivot = df.pivot_table(index=['Product'], values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
print(pivot)

              Amount
                mean median    min
Product
Banana    363.666667  384.0   90.0
Beans     626.000000  626.0  626.0
Broccoli  150.500000  150.5   62.0
Carrots   270.000000  270.0  270.0
Orange    610.000000  610.0  610.0

In [124]:
data={
    'Name':['a','b','c','d'],
     'Age' :[20,30,22,24]
}
df=pd.DataFrame(data)
print(df)

  Name  Age
0    a   20
1    b   30
2    c   22
3    d   24

In [125]:
salary=[50000,60000,70000,80000]
df['Sal']=salary
print(df)

  Name  Age    Sal
0    a   20  50000
1    b   30  60000
2    c   22  70000
3    d   24  80000

In [133]:
DF=pd.Series({'DAY1':101,'DAY2':202})
print(DF)

DAY1    101
DAY2    202
dtype: int64

In [134]:
import pandas as pd
ds=pd.Series([10,20,30])
print(ds)

0    10
1    20
2    30
dtype: int64

In [135]:
import pandas as pd
label=['a','b','c']
val=[10,20,30]
ds=pd.Series(val,index=label)
print(ds)

a    10
b    20
c    30
dtype: int64