In [1]:
import pandas as pd

In [2]:
out=pd.Series([10,20,30,40])
print(out)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
s=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [3]:
dat={
    'phy':90,'math':89
}
res=pd.Series(dat)
print(res)

phy     90
math    89
dtype: int64

In [3]:
prices=[100000,200000,300000,400000,500000]
carname=['Alto','Verna','BMW','SANTRO','MAHENDRA']
s=pd.Series(prices,carname)
print(s)

Alto        100000
Verna       200000
BMW         300000
SANTRO      400000
MAHENDRA    500000
dtype: int64

In [4]:
carname={
    'ALTO':500000,
    'BMW':700000,
    'SANTRO':800000
}
series=pd.Series(carname)
print(series)

ALTO      500000
BMW       700000
SANTRO    800000
dtype: int64

In [5]:
print(series<700000)

ALTO       True
BMW       False
SANTRO    False
dtype: bool

In [6]:
print(series[series<700000])

ALTO    500000
dtype: int64

In [7]:
print(series[series<700000].index[0])

ALTO

In [8]:
print(series[series<700000].values[0])

500000

In [9]:
print(series[(series<600000)]&series[(series<700000)])

ALTO    500000
dtype: int64

In [10]:
cust_names = ['Hemang', 'Farheen', 'Himadri', 'Monisha']
cust_bill = [256.78, 434.53, 109.25, 529.42]

cust_info = pd.Series(cust_bill, cust_names)
#Write Python code to print the names of the customers who have spent more than 300 rupees.
print(cust_info[cust_info>300])

Farheen    434.53
Monisha    529.42
dtype: float64

In [11]:
print(list(cust_info[cust_info>300].index))

['Farheen', 'Monisha']

In [12]:
#Accessing data from loc and iloc with single value and key pair

In [13]:
cust_info.loc['Hemang']

256.78

In [14]:
print(cust_info.loc[['Hemang']])

Hemang    256.78
dtype: float64

In [15]:
cust_info.iloc[0]

256.78

In [16]:
cust_info.loc[:]

Hemang     256.78
Farheen    434.53
Himadri    109.25
Monisha    529.42
dtype: float64

In [51]:
cust_info.loc[:]

Hemang     256.78
Farheen    434.53
Himadri    109.25
Monisha    529.42
dtype: float64

In [52]:
cust_info.iloc[1:3]

Farheen    434.53
Himadri    109.25
dtype: float64

In [19]:
cust_info.iloc[1]

434.53

In [20]:
cust_info.iloc[1:3]

Farheen    434.53
Himadri    109.25
dtype: float64

loc is inclusive stop value but iloc not inclusive

cust_names = ['Mahesh', 'Farheen', 'Himadri', 'Monisha']
cust_bill = [256.78, 434.53, 109.25, 529.42]
cust_info = pd.Series(cust_bill, cust_names)
Use the different methods you have studied to extract the bill amounts for Mahesh and Monisha.

# Handling Data Frames

Handling DataFrames
Definition & Functionality
Loading Data: Import CSV, Excel, or SQL files into Pandas DataFrames.

Inspecting Data: View structure, columns, and basic statistics.

Modifying Data: Add, rename, or remove columns.

In [21]:
#create data mannually
df=pd.DataFrame({
    'PRODUCT':['PEN','MARKER','BOARD'],
    'PRICE':[100,200,1000],
    'QUANTITY':[3,5,5]
    
})
print(df)

  PRODUCT  PRICE  QUANTITY
0     PEN    100         3
1  MARKER    200         5
2   BOARD   1000         5

In [22]:
df.to_csv("sales.csv",index=False)
print('sucess')

sucess

In [23]:
sales_data=pd.read_csv("sales.csv")
print(sales_data)

  PRODUCT  PRICE  QUANTITY
0     PEN    100         3
1  MARKER    200         5
2   BOARD   1000         5

In [24]:
print(sales_data['PRICE'])

0     100
1     200
2    1000
Name: PRICE, dtype: int64

In [25]:
print(sales_data[['PRICE','QUANTITY']])

   PRICE  QUANTITY
0    100         3
1    200         5
2   1000         5

In [32]:
file_path="indian_pharmaceutical_products_clean.csv"
data=pd.read_csv(file_path)

In [33]:
data.head(5)

,product_id,brand_name,manufacturer,price_inr,is_discontinued,dosage_form,pack_size,pack_unit,num_active_ingredients,primary_ingredient,primary_strength,active_ingredients,therapeutic_class,packaging_raw,manufacturer_raw
0,1,Augmentin 625 Duo Tablet,Glaxo SmithKline Pharmaceuticals Ltd,223.42,False,tablet,10.0,strip,2,Amoxycillin,500mg,"[{'name': 'Amoxycillin', 'strength': '500mg', ...",antibiotic,strip of 10 tablets,Glaxo SmithKline Pharmaceuticals Ltd
1,2,Azithral 500 Tablet,Alembic Pharmaceuticals Ltd,132.36,False,tablet,5.0,strip,1,Azithromycin,500mg,"[{'name': 'Azithromycin', 'strength': '500mg',...",antibiotic,strip of 5 tablets,Alembic Pharmaceuticals Ltd
2,3,Ascoril LS Syrup,Glenmark Pharmaceuticals Ltd,118.00,False,syrup,100.0,bottle,2,Ambroxol,30mg/5ml,"[{'name': 'Ambroxol', 'strength': '30mg/5ml', ...",bronchodilator,bottle of 100 ml Syrup,Glenmark Pharmaceuticals Ltd
3,4,Allegra 120mg Tablet,Sanofi India Ltd,218.81,False,tablet,10.0,strip,1,Fexofenadine,120mg,"[{'name': 'Fexofenadine', 'strength': '120mg',...",antihistamine,strip of 10 tablets,Sanofi India Ltd
4,5,Avil 25 Tablet,Sanofi India Ltd,10.96,False,tablet,15.0,strip,1,Pheniramine,25mg,"[{'name': 'Pheniramine', 'strength': '25mg', '...",other,strip of 15 tablets,Sanofi India Ltd

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253973 entries, 0 to 253972
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   product_id              253973 non-null  int64
 1   brand_name              253973 non-null  object
 2   manufacturer            253973 non-null  object
 3   price_inr               253973 non-null  float64
 4   is_discontinued         253973 non-null  bool
 5   dosage_form             253973 non-null  object
 6   pack_size               231643 non-null  float64
 7   pack_unit               231643 non-null  object
 8   num_active_ingredients  253973 non-null  int64
 9   primary_ingredient      253973 non-null  object
 10  primary_strength        228775 non-null  object
 11  active_ingredients      253973 non-null  object
 12  therapeutic_class       253973 non-null  object
 13  packaging_raw           253973 non-null  object
 14  manufacturer_raw        253973 non-null  object
dtypes: bool(1), float64(2), int64(2), object(10)
memory usage: 27.4+ MB

In [35]:
data.tail()

,product_id,brand_name,manufacturer,price_inr,is_discontinued,dosage_form,pack_size,pack_unit,num_active_ingredients,primary_ingredient,primary_strength,active_ingredients,therapeutic_class,packaging_raw,manufacturer_raw
253968,253969,Ziyapod 100mg Oral Suspension,Ziyana Lifesciences Pvt Ltd,62.3,False,suspension,30.0,bottle,1,Cefpodoxime Proxetil,100mg,"[{'name': 'Cefpodoxime Proxetil', 'strength': ...",other,bottle of 30 ml Oral Suspension,Ziyana Lifesciences Pvt Ltd
253969,253970,Zemhart 30mg Tablet,Leeford Healthcare Ltd,54.0,False,tablet,10.0,strip,1,Diltiazem,30mg,"[{'name': 'Diltiazem', 'strength': '30mg', 'fu...",other,strip of 10 tablets,Leeford Healthcare Ltd
253970,253971,Zivex 25mg Tablet,Euro Organics,57.0,False,tablet,10.0,strip,1,Hydroxyzine,25mg,"[{'name': 'Hydroxyzine', 'strength': '25mg', '...",other,strip of 10 tablets,Euro Organics
253971,253972,ZI Fast 500mg Injection,Burgeon Health Series Private Limited,152.0,False,injection,NaN,NaN,1,Azithromycin,500mg,"[{'name': 'Azithromycin', 'strength': '500mg',...",antibiotic,vial of 1 Injection,Burgeon Health Series Private Limited
253972,253973,Zyvocol 1% Dusting Powder,GBK Healthcare,110.0,False,powder,75.0,gm,1,Clotrimazole,NaN,"[{'name': 'Clotrimazole', 'strength': None, 'f...",other,bottle of 75 gm Dusting Powder,GBK Healthcare

In [36]:
data.describe()

          product_id      price_inr      pack_size  num_active_ingredients
count  253973.000000  253973.000000  231643.000000           253973.000000
mean   126987.000000     270.530844      18.988871                1.441893
std     73315.834296    3029.584134      36.717320                0.496795
min         1.000000       0.000000       1.000000                1.000000
25%     63494.000000      48.000000      10.000000                1.000000
50%    126987.000000      79.000000      10.000000                1.000000
75%    190480.000000     140.000000      10.000000                2.000000
max    253973.000000  436000.000000    5000.000000                5.000000

In [28]:
#Handling Missing Values,Aggregations & Sorting in Pandas

In [37]:
#missing values
missing=data.isnull().sum()
print('missingvalues:\n \n',missing)

missingvalues:

 product_id                    0
brand_name                    0
manufacturer                  0
price_inr                     0
is_discontinued               0
dosage_form                   0
pack_size                 22330
pack_unit                 22330
num_active_ingredients        0
primary_ingredient            0
primary_strength          25198
active_ingredients            0
therapeutic_class             0
packaging_raw                 0
manufacturer_raw              0
dtype: int64

In [38]:
nul=data.isnull()

In [39]:
nul

,product_id,brand_name,manufacturer,price_inr,is_discontinued,dosage_form,pack_size,pack_unit,num_active_ingredients,primary_ingredient,primary_strength,active_ingredients,therapeutic_class,packaging_raw,manufacturer_raw
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253968,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
253969,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
253970,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
253971,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False
253972,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False

In [40]:
data['pack_size']

0          10.0
1           5.0
2         100.0
3          10.0
4          15.0
          ...
253968     30.0
253969     10.0
253970     10.0
253971      NaN
253972     75.0
Name: pack_size, Length: 253973, dtype: float64

In [41]:
pack_s=data['pack_size'].median()

In [42]:
pack_s

10.0

In [43]:
data['pack_size'].fillna(pack_s,inplace=True)

In [44]:
data['pack_size']

0          10.0
1           5.0
2         100.0
3          10.0
4          15.0
          ...
253968     30.0
253969     10.0
253970     10.0
253971     10.0
253972     75.0
Name: pack_size, Length: 253973, dtype: float64

In [45]:
data['pack_unit']

0          strip
1          strip
2         bottle
3          strip
4          strip
           ...
253968    bottle
253969     strip
253970     strip
253971       NaN
253972        gm
Name: pack_unit, Length: 253973, dtype: object

In [46]:
mean_pack=data['pack_unit']

In [47]:
mean_pack

0          strip
1          strip
2         bottle
3          strip
4          strip
           ...
253968    bottle
253969     strip
253970     strip
253971       NaN
253972        gm
Name: pack_unit, Length: 253973, dtype: object